name: CSS (Dart Sass)
on: [push, pull_request]
env:
  CI: true
  NODE: 12.x

jobs:
  css:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Build CSS with Dart Sass
        run: |
          npx --package sass@1.26.11 sass --version
          npx --package sass@1.26.11 sass --style expanded --source-map --embed-sources --no-error-css scss/:dist-sass/css/
          ls -Al dist-sass/css
